name: Pull Request
on: [push]
jobs:
  lint:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
